# Generated by Django 5.0.6 on 2024-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('COMPANY', 'Company')], max_length=25, null=True),
        ),
    ]
