# Generated by Django 5.0.6 on 2024-06-13 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('type', models.CharField(choices=[('PART_TIME', 'Part Time'), ('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=25)),
                ('company', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('deadline', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
