# Generated by Django 5.0.6 on 2024-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
