# Generated by Django 5.0.6 on 2024-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('COMPANY', 'Company')], default='CANDIDATE', max_length=20)),
            ],
        ),
    ]
